course: "INT 5"
qtr: "F18"
quarter: "Fall 2018"
github_url: https://github.com/ucsb-int5-f18/ucsb-int5-f18.github.io

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/
    
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  -
    scope:
      path: ""
      type: hwk
    values:
      layout: default
  -
    scope:
      path: ""
      type: lab
    values:
      layout: default
  -
    scope:
      path: ""
      type: exam
    values:
      layout: default
  -
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: ""
      type: lectures
    values:
      layout: default
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: default
